service: hotel-api-set
app: hotelapiset
tenant: amanneox
custom:
  splitStacks:
    perFunction: false
    perType: true
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  createUser:
    handler: handlers/UserHandler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  createStaff:
    handler: handlers/StaffHandler.createStaff
    events:
      - http:
          path: staff
          method: post
          cors: true
  createBooking:
    handler: handlers/BookingHandler.createBooking
    events:
      - http:
          path: booking
          method: post
          cors: true
  createRoom:
    handler: handlers/RoomHandler.createRoom
    events:
      - http:
          path: room
          method: post
          cors: true

  createGrocery:
    handler: handlers/GroceryHandler.createGrocery
    events:
      - http:
          path: grocery
          method: post
          cors: true

  createAmenity:
    handler: handlers/AmenityHandler.createAmenity
    events:
      - http:
          path: amenity
          method: post
          cors: true

  createCustomer:
    handler: handlers/CustomerHandler.createCustomer
    events:
      - http:
          path: customer
          method: post
          cors: true

  createRoomType:
    handler: handlers/RoomTypeHandler.createRoomType
    events:
      - http:
          path: roomType
          method: post
          cors: true

  authenticate:
    handler: handlers/UserHandler.authenticate
    events:
      - http:
          path: user/authenticate
          method: post
          cors: true

  updateUser:
    handler: handlers/UserHandler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  updateStaff:
    handler: handlers/StaffHandler.updateStaff
    events:
      - http:
          path: staff/{id}
          method: put
          cors: true

  updateBooking:
    handler: handlers/BookingHandler.updateBooking
    events:
      - http:
          path: booking/{id}
          method: put
          cors: true

  updateCustomer:
    handler: handlers/CustomerHandler.updateCustomer
    events:
      - http:
          path: customer/{id}
          method: put
          cors: true

  updateRoom:
    handler: handlers/RoomHandler.updateRoom
    events:
      - http:
          path: room/{id}
          method: put
          cors: true

  updateGrocery:
    handler: handlers/GroceryHandler.updateGrocery
    events:
      - http:
          path: grocery/{id}
          method: put
          cors: true

  updateAmenity:
    handler: handlers/AmenityHandler.updateAmenity
    events:
      - http:
          path: amenity/{id}
          method: put
          cors: true
