service: hotel-api-set
app: hotelapiset
tenant: amanneox
custom:
  splitStacks:
    perFunction: false
    perType: true
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  createUser:
    handler: handlers/UserHandler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  createRoom:
    handler: handlers/RoomHandler.createRoom
    events:
      - http:
          path: room
          method: post
          cors: true

  createRoomType:
    handler: handlers/RoomTypeHandler.createRoomType
    events:
      - http:
          path: roomType
          method: post
          cors: true

  authenticate:
    handler: handlers/UserHandler.authenticate
    events:
      - http:
          path: user/authenticate
          method: post
          cors: true

  updateUser:
    handler: handlers/UserHandler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handlers/UserHandler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true
