service: hotel-api-get
app: hotelapiget
tenant: amanneox
custom:
  splitStacks:
    perFunction: false
    perType: true
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  user:
    handler: handlers/UserHandler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true
  room:
    handler: handlers/RoomHandler.room
    events:
      - http:
          path: room/{id}
          method: get
          cors: true
#  rent:
#    handler: handlers/RentHandler.rent
#    events:
#      - http:
#          path: rent/{id}
#          method: get
#          cors: true
  staff:
    handler: handlers/StaffHandler.staff
    events:
      - http:
          path: staff/{id}
          method: get
          cors: true
  booking:
    handler: handlers/BookingHandler.booking
    events:
      - http:
          path: booking/{id}
          method: get
          cors: true
  grocery:
    handler: handlers/GroceryHandler.grocery
    events:
      - http:
          path: grocery/{id}
          method: get
          cors: true
  amenity:
    handler: handlers/AmenityHandler.amenity
    events:
      - http:
          path: amenity/{id}
          method: get
          cors: true
  customer:
    handler: handlers/CustomerHandler.customer
    events:
      - http:
          path: customer/{id}
          method: get
          cors: true
  roomType:
    handler: handlers/RoomTypeHandler.roomType
    events:
      - http:
          path: roomType/{id}
          method: get
          cors: true

##  getUsers:
#    handler: handlers/UserHandler.getUsers
#    events:
#      - http:
#          path: user/list
#          method: get
#          cors: true

  getRooms:
    handler: handlers/RoomHandler.getRooms
    events:
      - http:
          path: room/list
          method: get
          cors: true
  getRents:
    handler: handlers/RentHandler.getRents
    events:
      - http:
          path: rent/list
          method: get
          cors: true
  getCustomers:
    handler: handlers/CustomerHandler.getCustomers
    events:
      - http:
          path: customer/list
          method: get
          cors: true

  getStaffs:
    handler: handlers/StaffHandler.getStaffs
    events:
      - http:
          path: staff/list
          method: get
          cors: true
  getBookings:
    handler: handlers/BookingHandler.getBookings
    events:
      - http:
          path: booking/list
          method: get
          cors: true
  getGrocerys:
    handler: handlers/GroceryHandler.getGrocerys
    events:
      - http:
          path: grocery/list
          method: get
          cors: true
  getAmenitys:
    handler: handlers/AmenityHandler.getAmenitys
    events:
      - http:
          path: amenity/list
          method: get
          cors: true

  deleteRoom:
    handler: handlers/RoomHandler.deleteRoom
    events:
      - http:
          path: room/delete/{id}
          method: get
          cors: true

  deleteRent:
    handler: handlers/RentHandler.deleteRent
    events:
      - http:
          path: rent/delete/{id}
          method: get
          cors: true

  deleteStaff:
    handler: handlers/StaffHandler.deleteStaff
    events:
      - http:
          path: staff/delete/{id}
          method: get
          cors: true

  deleteBooking:
    handler: handlers/BookingHandler.deleteBooking
    events:
      - http:
          path: booking/delete/{id}
          method: get
          cors: true
  deleteCustomer:
    handler: handlers/CustomerHandler.deleteCustomer
    events:
      - http:
          path: customer/delete/{id}
          method: get
          cors: true
  deleteGrocery:
    handler: handlers/GroceryHandler.deleteGrocery
    events:
      - http:
          path: grocery/delete/{id}
          method: get
          cors: true
#  deleteUser:
#    handler: handlers/UserHandler.deleteUser
#    events:
#      - http:
#          path: user/delete/{id}
#          method: get
#          cors: true
  getRoomTypes:
    handler: handlers/RoomTypeHandler.getRoomTypes
    events:
      - http:
          path: roomType/list
          method: get
          cors: true
