service: hotel-api
app: hotelapi
tenant: amanneox
provider:
  name: aws
  stage: dev
  region: ap-south-1
  runtime: nodejs8.10

functions:
  createUser:
    handler: handlers/UserHandler.createUser
    events:
      - http:
          path: user
          method: post
          cors: true

  authenticate:
    handler: handlers/UserHandler.authenticate
    events:
      - http:
          path: user/authenticate
          method: post
          cors: true

  updateUser:
    handler: handlers/UserHandler.updateUser
    events:
      - http:
          path: user/{id}
          method: put
          cors: true

  deleteUser:
    handler: handlers/UserHandler.deleteUser
    events:
      - http:
          path: user/{id}
          method: delete
          cors: true

  user:
    handler: handlers/UserHandler.user
    events:
      - http:
          path: user/{id}
          method: get
          cors: true

  listUsers:
    handler: handlers/UserHandler.listUsers
    events:
      - http:
          path: user/list
          method: get
          cors: true
